/*
 * This source file was generated by the Gradle 'init' task
 */
package cursos;

import cursos.model.Estudiante;
import java.util.Scanner;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
