/*
 * This source file was generated by the Gradle 'init' task
 */
package cursos;

import cursos.model.Estudiante;
import java.util.Scanner;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner lector = new Scanner(System.in);
        System.out.println(new App().getGreeting());

        // 1. Pedir la cantidad de alumnos
        System.out.print("Por favor, ingresa la cantidad de alumnos: ");
        int cantidad = lector.nextInt();

        System.out.println("Son " + cantidad + " alumnos");
    }
}
